Update UI delete workflow documentation
aqueducthq/gitbook pull request #14
Opened 2022-08-20 02:30 UTC by eunice-chan

Delete workflow can now additionally delete saved objects. Update documentation accordingly.

2022-08-23 22:41 UTC, likawind reviewed
Should we add some screenshots here? Also I'm wondering if we could generate some preview for the updated doc so that it's more intuitive to review the changes @vsreekanti

2022-08-23 23:02 UTC, vsreekanti requested changes
A couple clarifications. I agree with @likawind that adding a screenshot of the deletion UI would be nice.

2022-08-23 23:02 UTC, vsreekanti commented on workflows/deleting-a-workflow.md
> +You can delete the workflow by following the instructions. You are given the option to delete the entirety of any objects saved by the workflow.
I think we could add a bit more detailed here. The word "entirety" is carrying a lot of weight, which we should explain further. I would say two separate things: (1) you can choose which objects to delete; (2) any objects you pick will be completely deleted.

2022-08-23 23:02 UTC, vsreekanti commented on workflows/deleting-a-workflow.md
> +After workflow deletion has succeeded, if you delete any saved objects, you will be shown the results of the deletion (succeeded or failed) and any associated logs. Once you are done, you will be red
We should also clarify here that the workflow will be deleted regardless of whether the underlying objects are deleted.

2022-08-24 18:29 UTC, vsreekanti approved these changes
I left one edit inline @eunice-chan, but this is good!

2022-08-24 18:29 UTC, vsreekanti commented on workflows/deleting-a-workflow.md
> +After workflow deletion has succeeded, if you delete any saved objects, you will be shown the results of the deletion (succeeded or failed) and any associated logs. Object deletion is done best-effor
The content is good, but the wording is a little confusing. Let's try something like this: 
> Once you confirm deletion of the workflow, Aqueduct will delete the workflow's metadata as well as any of the data objects you selected on the previous screen. Object deletion is done best-effort, and the workflow will be deleted whether or not the associated objects are successfully deleted. After workflow deletion has completed, you will be shown a list of all the objects that Aqueduct attempted to delete and whether those delete operations succeeded or not.

2022-08-25 17:07 UTC, merged